### PR TITLE
Engine parameter targets node 10+

### PR DESCRIPTION
**Pull request by aalykiot**

### CODE REVIEW

**Comment by lholmquist** [comment]
looks like there are some linting issues now that the engine is node 10+

**Comment by aalykiot** [comment]
@lholmquist Looking at the Travis CI logs I'm seeing the following errors

test/kube-probe-test.js:16:6

  ✖   16:6   Prefer await to then().                                        promise/prefer-await-to-then

  ✖   29:6   Prefer await to then().                                        promise/prefer-await-to-then

  ✖   49:6   Prefer await to then().                                        promise/prefer-await-to-then

  ✖   69:6   Prefer await to then().                                        promise/prefer-await-to-then

  ✖   83:6   Prefer await to then().                                        promise/prefer-await-to-then

  ✖   97:6   Prefer await to then().                                        promise/prefer-await-to-then

  ✖  116:6   Prefer await to then().                                        promise/prefer-await-to-then

  index.js:23:22

  ✖   23:22  Use an object spread instead of Object.assign eg: { ...foo }.  prefer-object-spread

**Comment by lholmquist** [comment]
those "prefer await to then" should be pretty easy to fix.

and the "prefer spread" should be something like this:

```
const protectCfg = {
    production: process.env.NODE_ENV === 'production',
    maxHeapUsedBytes: 0,
    maxRssBytes: 0, 
    ...options.protectionConfig
  };
```

There is some good info here, https://thecodebarbarian.com/object-assign-vs-object-spread.html, about how Object.Assign and spread relate to each other

**Comment by aalykiot** [comment]
@lholmquist Done! Everything is fixed ;)

**Review by lholmquist — APPROVED** [review]

**Pull request merged**
